language: java
jdk:
  - oraclejdk8

env:
  - BUILD_TOOL=maven
  - BUILD_TOOL=gradle

script:
  - ./build.sh

after_success:
  - mvn clean test jacoco:report coveralls:report -pl catwatch-backend -Pjacoco

notifications:
  email:
    - angela.igreja@zalando.de 
    - ruben.barilani@zalando.de 
    - roman.bobin@zalando.de 
    - manuel.kunz@zalando.de 
    - frank.schulze@zalando.de 
    - priyadarshini.maji@zalando.de 
    - rodrigo.witzel@zalando.de 

