swagger: "2.0"

info:
  version: "0.0.1-alpha"
  title: Birdwatch API
  description: BirdWatch presents statistics about your most popular projects on github.com and your most active contributors. The results are accessible via REST API and statistics website.

schemes:
  - https

basePath: /api

consumes:
  - application/json
produces:
  - application/json

definitions:

  Stats:
    type: object
    properties:
      forks:
        type: string
        example: "223"
      stars:
        type: string
        example: "34"
      contributors:
        type: string
        example: "34"
      overall:
        $ref: "#/definitions/Action"
      last_month:
        $ref: "#/definitions/Action"

  Action:
    type: object
    properties:
      commits:
        type: string
        example: "23"
      pull_request:
        type: string
        example: "77"
      comments:
        type: string
        example: "44"
      approvals:
        type: string
        example: "66"

  Project:
    type: object
    properties:
      external:
        type: boolean
        example: true
      name:
        type: string
        example: birdwatch
      description:
        type: string
        example: "describe me"
      url:
        type: string
        example: "https://github.com/zalando/birdwatch"
      programming_language:
        type: string
        example: "python"
      logo_url:
        type: string
        example: "https://avatars2.githubusercontent.com/u/1564818?v=3&s=200"
      checks:
        type: object
        properties:
          licence:
            type: string
            example: "Apache 2"
          readme:
            type: boolean
            example: false
          mantainers:
            type: string
            example: "test@test.test"
          travis_ci:
            type: string
            example: "successfull"
          coveralls:
            type: string
            example: "10 of 1000 lines covered"
          pypi:
            type: string
            example: "100000 download this month"
          zombies:
            type: boolean
            example: true
      stats:
        $ref: "#/definitions/Stats"


  Contributor:
    type: object
    properties:
      name:
        type: string
        example: "Michele Randi"
      avatar_url:
        type: string
        example: "https://github.com/avatar/q34rew.jpg"
      username:
        type: string
        example: "mrandi"
      stats:
        $ref: "#/definitions/Stats"

paths:

  ## Birdwatch API

  /projects:
    get:
      summary: projects
      description: Get all projects
      tags:
        - Birdwatch API
      operationId: blub
      parameters:
        - name: order_by
          in: query
          type: string
          enum:
            - POPULAR
            - ACTIVE
      responses:
        "200":
          description: List of all projects
          schema:
            type: array
            items:
              $ref: "#/definitions/Project"

  /contributors:
    get:
      summary: contributors
      description: Get all contributors
      tags:
        - Birdwatch API
      operationId: blub
      parameters:
        - name: order_by
          in: query
          type: string
          enum:
            - POPULAR
            - ACTIVE
          required: true

      responses:
        "200":
          description: List of all contributors
          schema:
            type: array
            items:
              $ref: "#/definitions/Contributor"
